# Notebook to explore the UWHVF dataset

In-depth description of the dataset: https://pubmed.ncbi.nlm.nih.gov/34978561/

In [50]:
import json
import numpy as np
from pathlib import Path

In [51]:
UWHVF_DIR = Path("../data") / "UWHVF"
ALL_DATA_FILENAME = UWHVF_DIR / "alldata.json"

In [85]:
# Load data
with open(ALL_DATA_FILENAME) as f:
  data = json.loads(f.read())

# Optional: pretty dump json to file
# with open(ALL_DATA_FILENAME, "w") as f:
#   json.dump(data, f, indent=4)

In [99]:
print(f"Num humphrey visual fields (HVFs): {data["hvfs"]}")
print(f"Num eyes: {data["eyes"]}")
print(f"Num patients: {data["pts"]}")
# print(f"Measured points in VF grid: {data["coords"]}")

Num humphrey visual fields (HVFs): 28943
Num eyes: 7428
Num patients: 3871


## Measurements for a patient

In [89]:
PATIENT_ID = '647'
EYE = 'R' # or 'L'
NUM_MEASUREMENTS = len(data["data"][PATIENT_ID][EYE])
print(f"Num measurements of the eye {EYE} for patient {PATIENT_ID}: {NUM_MEASUREMENTS}")

Num measurements of the eye R for patient 647: 11


## Humphrey Visual Field (HVF) and Total Deviation (TD) for a specific measurement

In [98]:
MEASUREMENT_ID = 0
print(f"Measurement: {MEASUREMENT_ID} (of {NUM_MEASUREMENTS}) for the eye {EYE} or patient {PATIENT_ID}")
print(f"Age of patient at measurement: {data['data'][PATIENT_ID]['R'][MEASUREMENT_ID]['age']}\n")
print("Humphrey visual field:")
print(f"{np.array(data['data'][PATIENT_ID]['R'][MEASUREMENT_ID]['hvf'])}\n")
print("Total deviation (difference in retinal sensitivity at each tested point compared to \n" \
"an age-matched normal database, expressed in decibels (dB)):")
print(np.array(data['data'][PATIENT_ID]['R'][MEASUREMENT_ID]['td']))

Measurement: 0 (of 11) for the eye R or patient 647
Age of patient at measurement: 52.79671457905544

Humphrey visual field:
[[100.   100.   100.    26.34  23.73  22.84  24.19 100.   100.  ]
 [100.   100.    26.25  27.22  25.67  26.18  27.01  26.24 100.  ]
 [100.    22.2   28.17  29.2   28.44  27.58  28.51  28.02  25.68]
 [ 20.4   27.41  29.73  30.02  30.93  30.36  30.64  21.    27.89]
 [ 20.45  25.88  28.9   32.17  31.89  30.91  28.8    0.    27.43]
 [100.    27.16  29.98  32.74  29.95  32.07  29.84  26.99  27.3 ]
 [100.   100.    26.88  29.43  29.82  28.64  29.81  28.24 100.  ]
 [100.   100.   100.    28.88  27.3   26.82  28.18 100.   100.  ]]

Total deviation (difference in retinal sensitivity at each tested point compared to 
an age-matched normal database, expressed in decibels (dB)):
[[100.   100.   100.    -3.23  -5.88  -6.43  -4.72 100.   100.  ]
 [100.   100.    -4.77  -4.51  -6.26  -5.42  -4.09  -4.29 100.  ]
 [100.    -8.91  -4.39  -4.18  -5.29  -5.85  -4.3   -3.97  -5.51]
 